version: '2'
services: 
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./conf/mysql:/etc/mysql/conf.d"
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: jira
      MYSQL_DATABASE: jira
      MYSQL_USER: materliu
      MYSQL_PASSWORD: jira

  jira:
    depends_on:
      - db
    image: cptactionhank/atlassian-jira-software:latest    
    links:
      - db
    ports:
      - "10010:8080"
    restart: always    
    environment: 
      JIRA_DB_HOST: db:3306
      JIRA_DB_PASSWORD: jira
      JIRA_DB_USER: materliu
      JIRA_DB_NAME: jira  

